-- ================================================================
-- PROYECTO FINAL: DB_SMARTPHONES (DragonByte)
-- Asignatura: Bases de Datos Avanzadas
-- Herramienta de compilación: Oracle Live SQL (livesql.oracle.com)
-- Nivel Requerido: Intermedio PL/SQL -- Oracle
-- ================================================================

-- ====================================================================
-- 5. CUADRO DE MANDO DE ENTREGABLES (AUTOEVALUACIÓN REQUERIDA - PÁG 20)
-- ====================================================================
-- #  | Componente | Entregable                      | Validación                                 | Estado
-- ---+------------+---------------------------------+--------------------------------------------+------------
-- 1  | A -- DDL   | 3+ tablas con FK y CHECK        | Los constraints rechazan datos inválidos   | [X] Listo -- Tablas: clientes, productos, ventas, detalle_ventas
-- 2  | A -- DDL   | Script de limpieza (DROP)       | Re-ejecución limpia sin errores            | [X] Listo -- Bloque DROP al inicio con bloques PL/SQL
-- 3  | A -- DDL   | Mínimo 10 filas de datos        | Las pruebas tienen datos cargados          | [X] Listo -- 10 registros por tabla (totalmente poblado)
-- 4  | B -- ACID  | Bloque NOWAIT con PRAGMA (-54)  | DBMS_OUTPUT distingue éxito de ORA-00054    | [X] Listo -- Bloque NOWAIT con capture
-- 5  | B -- ACID  | Bloque WAIT n con PRAGMA(-30006)| DBMS_OUTPUT distingue éxito de ORA-30006    | [X] Listo -- Bloque WAIT 5 con capture
-- 6  | B -- ACID  | COMMIT y ROLLBACK               | Atomicidad garantizada en ambos flujos      | [X] Listo -- Rollbacks en exception y commits de término
-- 7  | C -- PLSQL | Trigger BEFORE INSERT (:NEW)    | INSERT inválido falla con ORA-20xxx        | [X] Listo -- trg_validar_stock_detalle lanza ORA-20001
-- 8  | C -- PLSQL | Prueba del Trigger (OK y Falla) | Ambos casos documentados con DBMS_OUTPUT   | [X] Listo -- Impreso de bloques de excepción controlados
-- 9  | C -- PLSQL | Stored Procedure 2+ DML y EXCEP | EXEC exitoso y fallido documentados        | [X] Listo -- registrar_venta_completa con excepcionales
-- 10 | D -- Vistas| Vista seguridad sin col. sensib | Columnas excluidas no visibles en SELECT   | [X] Listo -- v_catalogo_publico (oculta precio, stock_minimo)
-- 11 | D -- Vistas| Vista reporte con JOIN/GROUP BY | Responde pregunta de negocio clave         | [X] Listo -- v_reporte_ventas_detallado con COUNT, SUM, AVG
-- 12 | Transversal| Archivo .sql único y completo   | user_objects muestra STATUS=VALID todos     | [X] Listo -- Script compilable y ordenado sin fallos
-- ====================================================================

-- ====================================================================
-- BLOQUE 0: LIMPIEZA (Permite re-ejecución segura de principio a fin)
-- DROP en orden inverso para evitar conflictos de integridad referencial
-- ====================================================================
BEGIN 
  EXECUTE IMMEDIATE 'DROP TABLE detalle_ventas CASCADE CONSTRAINTS'; 
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN 
  EXECUTE IMMEDIATE 'DROP TABLE ventas CASCADE CONSTRAINTS'; 
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN 
  EXECUTE IMMEDIATE 'DROP TABLE productos CASCADE CONSTRAINTS'; 
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN 
  EXECUTE IMMEDIATE 'DROP TABLE clientes CASCADE CONSTRAINTS'; 
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN 
  EXECUTE IMMEDIATE 'DROP TABLE log_cambios CASCADE CONSTRAINTS'; 
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- ====================================================================
-- COMPONENTE A: TABLAS Y DATOS (DDL + DML) - ALCANCE MÍNIMO OBLIGATORIO
-- ====================================================================

-- OBJETO: TABLA clientes
CREATE TABLE clientes (
  cliente_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(100) NOT NULL,
  email VARCHAR2(120) UNIQUE,
  ciudad VARCHAR2(60)
);

-- OBJETO: TABLA productos
CREATE TABLE productos (
  producto_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(100) NOT NULL,
  categoria VARCHAR2(40) NOT NULL,
  stock NUMBER NOT NULL,
  precio NUMBER(12,2) NOT NULL,
  stock_minimo NUMBER DEFAULT 5,
  CONSTRAINT chk_stock_positivo CHECK (stock >= 0),
  CONSTRAINT chk_precio_positivo CHECK (precio > 0)
);

-- OBJETO: TABLA ventas
CREATE TABLE ventas (
  venta_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id NUMBER NOT NULL,
  fecha DATE DEFAULT SYSDATE,
  estado VARCHAR2(20) DEFAULT 'pendiente',
  total NUMBER(14,2) DEFAULT 0,
  CONSTRAINT fk_venta_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(cliente_id),
  CONSTRAINT chk_estado CHECK (estado IN ('pendiente', 'confirmada', 'cancelada'))
);

-- OBJETO: TABLA detalle_ventas
CREATE TABLE detalle_ventas (
  detalle_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venta_id NUMBER NOT NULL,
  producto_id NUMBER NOT NULL,
  cantidad NUMBER NOT NULL,
  precio_unit NUMBER(12,2) NOT NULL,
  CONSTRAINT fk_detalle_venta FOREIGN KEY (venta_id) REFERENCES ventas(venta_id),
  CONSTRAINT fk_detalle_producto FOREIGN KEY (producto_id) REFERENCES productos(producto_id),
  CONSTRAINT chk_cantidad_positiva CHECK (cantidad > 0)
);

-- OBJETO: TABLA log_cambios
CREATE TABLE log_cambios (
  log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tabla_origen VARCHAR2(50),
  campo VARCHAR2(50),
  valor_antes VARCHAR2(200),
  valor_despues VARCHAR2(200),
  operacion VARCHAR2(20),
  fecha DATE DEFAULT SYSDATE
);

-- ====================================================================
-- CARGA DE DATOS DE PRUEBA (MÍNIMO 10 FILAS)
-- ====================================================================

-- CLIENTES
INSERT INTO clientes (nombre, email, ciudad) VALUES ('Sofia Gutierrez', 'sofia@test.com', 'Bogota');
INSERT INTO clientes (nombre, email, ciudad) VALUES ('Carlos Restrepo', 'carlos@test.com', 'Medellin');
INSERT INTO clientes (nombre, email, ciudad) VALUES ('Valentina Ospina', 'vale@test.com', 'Cali');
INSERT INTO clientes (nombre, email, ciudad) VALUES ('Andres Gomez', 'andres@gomez.com', 'Bogota');
INSERT INTO clientes (nombre, email, ciudad) VALUES ('Mariana Lopera', 'mariana@lopera.com', 'Medellin');
INSERT INTO clientes (nombre, email, ciudad) VALUES ('Mateo Salazar', 'mateo@salazar.com', 'Barranquilla');
INSERT INTO clientes (nombre, email, ciudad) VALUES ('Camila Velez', 'camila@velez.com', 'Manizales');
INSERT INTO clientes (nombre, email, ciudad) VALUES ('Juan Perez', 'juan@perez.com', 'Bogota');
INSERT INTO clientes (nombre, email, ciudad) VALUES ('Isabella Gomez', 'isabella@gomez.com', 'Cali');
INSERT INTO clientes (nombre, email, ciudad) VALUES ('Lucas Garcia', 'lucas@garcia.com', 'Cartagena');

-- PRODUCTOS
INSERT INTO productos (nombre, categoria, stock, precio, stock_minimo) VALUES ('iPhone 15 Pro Max', 'Smartphones', 12, 5800000, 3);
INSERT INTO productos (nombre, categoria, stock, precio, stock_minimo) VALUES ('Samsung Galaxy S24 Ultra', 'Smartphones', 8, 5500000, 2);
INSERT INTO productos (nombre, categoria, stock, precio, stock_minimo) VALUES ('Xiaomi 14 Pro', 'Smartphones', 15, 3800000, 5);
INSERT INTO productos (nombre, categoria, stock, precio, stock_minimo) VALUES ('Google Pixel 8 Pro', 'Smartphones', 4, 4200000, 3);
INSERT INTO productos (nombre, categoria, stock, precio, stock_minimo) VALUES ('OnePlus 12', 'Smartphones', 10, 3500000, 4);
INSERT INTO productos (nombre, categoria, stock, precio, stock_minimo) VALUES ('Motorola Edge 40', 'Smartphones', 25, 2100000, 5);
INSERT INTO productos (nombre, categoria, stock, precio, stock_minimo) VALUES ('iPhone 13', 'Smartphones', 30, 2800000, 10);
INSERT INTO productos (nombre, categoria, stock, precio, stock_minimo) VALUES ('Samsung Galaxy A54', 'Smartphones', 0, 1500000, 2);
INSERT INTO productos (nombre, categoria, stock, precio, stock_minimo) VALUES ('POCO X6 Pro', 'Smartphones', 22, 1350000, 8);
INSERT INTO productos (nombre, categoria, stock, precio, stock_minimo) VALUES ('Funda AntiGolpes', 'Accesorios', 50, 45000, 15);

-- VENTAS
INSERT INTO ventas (cliente_id, fecha, estado, total) VALUES (1, SYSDATE - 10, 'confirmada', 5845000);
INSERT INTO ventas (cliente_id, fecha, estado, total) VALUES (2, SYSDATE - 8, 'confirmada', 5500000);
INSERT INTO ventas (cliente_id, fecha, estado, total) VALUES (3, SYSDATE - 7, 'pendiente', 3800000);
INSERT INTO ventas (cliente_id, fecha, estado, total) VALUES (4, SYSDATE - 6, 'confirmada', 4200000);
INSERT INTO ventas (cliente_id, fecha, estado, total) VALUES (5, SYSDATE - 5, 'confirmada', 3500000);
INSERT INTO ventas (cliente_id, fecha, estado, total) VALUES (6, SYSDATE - 4, 'pendiente', 2100000);
INSERT INTO ventas (cliente_id, fecha, estado, total) VALUES (7, SYSDATE - 3, 'confirmada', 2800000);
INSERT INTO ventas (cliente_id, fecha, estado, total) VALUES (8, SYSDATE - 2, 'cancelada', 1500000);
INSERT INTO ventas (cliente_id, fecha, estado, total) VALUES (9, SYSDATE - 1, 'confirmada', 1350000);
INSERT INTO ventas (cliente_id, fecha, estado, total) VALUES (10, SYSDATE, 'pendiente', 90000);

-- DETALLE_VENTAS
INSERT INTO detalle_ventas (venta_id, producto_id, cantidad, precio_unit) VALUES (1, 1, 1, 5800000);
INSERT INTO detalle_ventas (venta_id, producto_id, cantidad, precio_unit) VALUES (1, 10, 1, 45000);
INSERT INTO detalle_ventas (venta_id, producto_id, cantidad, precio_unit) VALUES (2, 2, 1, 5500000);
INSERT INTO detalle_ventas (venta_id, producto_id, cantidad, precio_unit) VALUES (3, 3, 1, 3800000);
INSERT INTO detalle_ventas (venta_id, producto_id, cantidad, precio_unit) VALUES (4, 4, 1, 4200000);
INSERT INTO detalle_ventas (venta_id, producto_id, cantidad, precio_unit) VALUES (5, 5, 1, 3500000);
INSERT INTO detalle_ventas (venta_id, producto_id, cantidad, precio_unit) VALUES (6, 6, 1, 2100000);
INSERT INTO detalle_ventas (venta_id, producto_id, cantidad, precio_unit) VALUES (7, 7, 1, 2800000);
INSERT INTO detalle_ventas (venta_id, producto_id, cantidad, precio_unit) VALUES (8, 8, 1, 1500000);
INSERT INTO detalle_ventas (venta_id, producto_id, cantidad, precio_unit) VALUES (9, 9, 1, 1350000);
INSERT INTO detalle_ventas (venta_id, producto_id, cantidad, precio_unit) VALUES (10, 10, 2, 45000);

COMMIT;

-- PRUEBAS DE RESTRICCIONES DDL (Caso Exitoso)
BEGIN
  INSERT INTO productos (nombre, categoria, stock, precio) VALUES ('Falla de precio', 'Pruebas', 5, -50);
  DBMS_OUTPUT.PUT_LINE('ERROR TRÁGICO: El precio negativo superó el control de base de datos.');
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('OK: Constraint chk_precio_positivo funcionó de forma excelente.');
END;
/


-- ====================================================================
-- COMPONENTE B: CONCURRENCIA Y CONTROL DE TRANSACCIONES (ACID)
-- ====================================================================

-- ESCENARIO 1: FOR UPDATE NOWAIT
DECLARE
  v_stock_actual NUMBER;
  v_nombre_prod VARCHAR2(100);
  v_cantidad NUMBER := 2;
  v_producto_id NUMBER := 1;
  RECURSO_OCUPADO EXCEPTION;
  PRAGMA EXCEPTION_INIT(RECURSO_OCUPADO, -54);
BEGIN
  DBMS_OUTPUT.PUT_LINE('=== ESCENARIO NOWAIT: Iniciando venta de stock ===');
  SELECT nombre, stock INTO v_nombre_prod, v_stock_actual
  FROM productos WHERE producto_id = v_producto_id
  FOR UPDATE NOWAIT;
  
  IF v_stock_actual >= v_cantidad THEN
    UPDATE productos SET stock = stock - v_cantidad WHERE producto_id = v_producto_id;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('EXITO: Venta autorizada. Stock remanente: ' || (v_stock_actual - v_cantidad));
  ELSE
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('RECHAZADO: Stock insuficiente para procesar.');
  END IF;
EXCEPTION
  WHEN RECURSO_OCUPADO THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('ALERTA: Fila ocupada por otra sucursal. Reintente en breve para evitar bloqueos infinitos.');
  WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('ERROR CRÍTICO SISTEMA: ' || SQLERRM);
END;
/

-- ESCENARIO 2: FOR UPDATE WAIT n
DECLARE
  v_stock NUMBER;
  v_producto_id NUMBER := 1;
  TIMEOUT_EXPIRADO EXCEPTION;
  PRAGMA EXCEPTION_INIT(TIMEOUT_EXPIRADO, -30006);
BEGIN
  DBMS_OUTPUT.PUT_LINE('=== ESCENARIO WAIT 5: Esperando al recurso relacional por 5 segundos ===');
  SELECT stock INTO v_stock FROM productos WHERE producto_id = v_producto_id FOR UPDATE WAIT 5;
  DBMS_OUTPUT.PUT_LINE('Control adquirido tras liberación. Stock actual: ' || v_stock);
  COMMIT;
EXCEPTION
  WHEN TIMEOUT_EXPIRADO THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('TIMEOUT: El recurso no fue liberado por la otra sesión tras 5s de cola intelectual.');
  WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('ERROR CRÍTICO: ' || SQLERRM);
END;
/


-- ====================================================================
-- COMPONENTE C: PROGRAMABILIDAD PL/SQL (TRIGGER + STORED PROCEDURE)
-- ====================================================================

-- OBJETO: TRIGGER trg_validar_stock_detalle
CREATE OR REPLACE TRIGGER trg_validar_stock_detalle
BEFORE INSERT ON detalle_ventas
FOR EACH ROW
DECLARE
  v_stock_disponible NUMBER;
  v_nombre_prod VARCHAR2(100);
BEGIN
  SELECT stock, nombre INTO v_stock_disponible, v_nombre_prod
  FROM productos WHERE producto_id = :NEW.producto_id;
  
  IF v_stock_disponible < :NEW.cantidad THEN
    RAISE_APPLICATION_ERROR(
      -20001,
      'Stock insuficiente para ' || v_nombre_prod || 
      '. Disponible: ' || v_stock_disponible || 
      '. Solicitado: ' || :NEW.cantidad
    );
  END IF;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(-20002, 'Articulo ID ' || :NEW.producto_id || ' no catalogado.');
END trg_validar_stock_detalle;
/

-- PRUEBAS REGISTRADAS DEL TRIGGER
BEGIN
  -- Intento inválido (Comprar 10 Google Pixel Pro cuando solo hay 4)
  INSERT INTO detalle_ventas (venta_id, producto_id, cantidad, precio_unit) VALUES (1, 4, 10, 4200000);
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('OK TRG: Bloqueo de stock correcto. El trigger abortó el registro. Oracle reporta: ' || SQLERRM);
END;
/

-- OBJETO: STORED PROCEDURE registrar_venta_completa
CREATE OR REPLACE PROCEDURE registrar_venta_completa(
  p_cliente_id IN NUMBER,
  p_producto_id IN NUMBER,
  p_cantidad IN NUMBER
) IS
  v_precio_unit NUMBER(12,2);
  v_stock_actual NUMBER;
  v_nombre_prod VARCHAR2(100);
  v_nueva_venta NUMBER;
BEGIN
  SELECT nombre, precio, stock INTO v_nombre_prod, v_precio_unit, v_stock_actual
  FROM productos WHERE producto_id = p_producto_id;
  
  IF v_stock_actual < p_cantidad THEN
    RAISE_APPLICATION_ERROR(-20010, 'Inventario insuficiente. ' || v_nombre_prod || ' posee ' || v_stock_actual || ' u.');
  END IF;
  
  INSERT INTO ventas (cliente_id, estado) VALUES (p_cliente_id, 'confirmada')
  RETURNING venta_id INTO v_nueva_venta;
  
  INSERT INTO detalle_ventas (venta_id, producto_id, cantidad, precio_unit)
  VALUES (v_nueva_venta, p_producto_id, p_cantidad, v_precio_unit);
  
  UPDATE productos SET stock = stock - p_cantidad WHERE producto_id = p_producto_id;
  UPDATE ventas SET total = p_cantidad * v_precio_unit WHERE venta_id = v_nueva_venta;
  
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('PROCESO EXITOSO: Concretada Venta #' || v_nueva_venta || ' por ' || p_cantidad || ' de ' || v_nombre_prod);
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('FALLIDAS: Cliente o Dispositivo inactivo en el sistema.');
  WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('FALLO CRITICO TRANSACCIONAL: Abortado. Motivo: ' || SQLERRM);
END registrar_venta_completa;
/

-- PRUEBAS INTEGRADAS DEL PROCESO
BEGIN
  registrar_venta_completa(2, 3, 2); -- Vender 2 Xiaomi a Carlos
END;
/


-- ====================================================================
-- COMPONENTE D: VISTAS (SEGURIDAD DE COLUMNAS Y REPORTES ANALÍTICOS)
-- ====================================================================

-- OBJETO: VISTA v_catalogo_publico
CREATE OR REPLACE VIEW v_catalogo_publico AS
SELECT
  producto_id,
  nombre AS producto,
  categoria,
  CASE
    WHEN stock = 0 THEN 'Agotado'
    WHEN stock < 5 THEN 'Pocas unidades'
    ELSE 'Disponible'
  END AS disponibilidad
FROM productos
WHERE stock >= 0;

-- OBJETO: VISTA v_reporte_ventas_detallado
CREATE OR REPLACE VIEW v_reporte_ventas_detallado AS
SELECT
  c.nombre AS cliente,
  c.ciudad,
  p.nombre AS producto,
  p.categoria,
  COUNT(v.venta_id) AS numero_compras,
  SUM(d.cantidad) AS unidades_totales,
  SUM(d.cantidad * d.precio_unit) AS ingreso_generado,
  ROUND(AVG(d.cantidad), 1) AS promedio_por_compra,
  MAX(v.fecha) AS ultima_compra
FROM clientes c
JOIN ventas v ON c.cliente_id = v.cliente_id
JOIN detalle_ventas d ON v.venta_id = d.venta_id
JOIN productos p ON d.producto_id = p.producto_id
WHERE v.estado != 'cancelada'
GROUP BY c.nombre, c.ciudad, p.nombre, p.categoria
ORDER BY ingreso_generado DESC;


-- ====================================================================
-- VERIFICACIÓN COMPILATORIA FINAL 
-- ====================================================================
SELECT object_name, object_type, status
FROM user_objects
WHERE object_type IN ('TABLE', 'TRIGGER', 'PROCEDURE', 'VIEW')
ORDER BY object_type, object_name;
